kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: voip-manager
  namespace: voip
rules:
  - apiGroups: [""] # "" indicates the core API group
    resources: ["pods","endpoints","services","nodes"]
    verbs: ["get", "watch", "list"]
  - apiGroups: ["apps"]
    resources: ["deployments"]
    verbs: ["get", "watch", "list", "update", "patch"]

---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: manager
  namespace: voip
subjects:
  - kind: User
    name: system:serviceaccount:voip:default
    apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: Role
  name: voip-manager
  apiGroup: rbac.authorization.k8s.io
